### ISSUE TITLE
View previous reports

### ISSUE THREAD

**Issue by MrUnknownGamer** [MinIsMin/NotYetTDM#10]
As a player, view previously made reports. View your message, their response, the admin handling, and the status of the reports. You can only see your reports. Do this by typing !preports (Previous Reports)

Currently working on this feature, should be done no more than a week.

**Comment by MinIsMin** [comment]
Would be a great feature. But then there should be also a feature for admins, showing all reports.

**Comment by MrUnknownGamer** [comment]
They have that in f8 silly :P

**Comment by MinIsMin** [comment]
But only for the previous map

**Comment by MrUnknownGamer** [comment]
Ahh, maybe I'll get that working once I get it to work for the current map

**Comment by MrUnknownGamer** [comment]
Done. Forgot to close
