### ISSUE TITLE
Use string.format for translating

### ISSUE THREAD

**Issue by MinIsMin** [MinIsMin/NotYetTDM#14]
Until now we are using `TTTLogTranslate()` for translating strings.
But this can cause issues when the sentence construction is different in English, German or French.
In easy sentences it works (English: "Tim reported you.", German: "Tim hat dich gemeldet.").
(I currently don't know an example for harder sentences)

We could use the function [string.format()](https://wiki.garrysmod.com/page/string/format), which works like this (taken from GarrysMod): 
`string.format("Hey '%s' - You're in the '%s' group on this server.", SteamIDs[steamid].name, SteamIDs[steamid].group)`

In TDM it would be used like this:
`string.format(TTTLogTranslate(GetDMGLogLang, "ReportedYou"), reporter:Name())`
- The string ReportedYou in lang.lua is "%s has reported you."
- The output will be "Tim has reported you."

I'd like you to share your opinion on this.
(I don't know why we didn't do it in the first place)
If you're ok with it I will update all language strings.

**Comment by Tommy228** [comment]
Yes, I think that's a good idea. I also had this problem while translating.

**Comment by MrUnknownGamer** [comment]
Good idea, agreed.
