### ISSUE TITLE
Move the Settings tab on the Damagelogs to the F1 menu

### ISSUE THREAD

**Issue by Tommy228** [MinIsMin/NotYetTDM#8]
I think that would be better. And eventually only show the weapons related stuff to the admins.

**Comment by MrUnknownGamer** [comment]
Just the language thing or the WHOLE menu? If so, I think the coloring for events should remain in the F1 settings and the language should go in F1. I don't think moving everything over is correct.

**Comment by Tommy228** [comment]
Why not moving everything? I don't see the point of having 2 settings tabs.

**Comment by MrUnknownGamer** [comment]
That's like asking to move the Ulx settings tab to the spawn menu in sandbox and darkrp. What's Min's opinion?

**Comment by Tommy228** [comment]
I'll do it, and we'll see how it goes.
