### ISSUE TITLE
Can't load old logs

### ISSUE THREAD

**Issue by MinIsMin** [MinIsMin/NotYetTDM#9]
Since last update from Tommy, I can't load any old logs (using sqlite).

I think the suffix _v3 from damagelog_oldlogs is one issue.
Also, the console prints: `no such column: year`

**Comment by MrUnknownGamer** [comment]
Be sure to keep the _v3. It is used so the old logs don't conflict with the new saving method Tommy made.

**Comment by MinIsMin** [comment]
Ah ok, a new saving method. Problem is on my server the rounds aren't saved (or loaded?)

**Comment by MrUnknownGamer** [comment]
I wonder if I pushed the fix. Let me check, I had the same problem.

**Comment by MrUnknownGamer** [comment]
Seems I didn't, I pushed the fix. Test it now

**Comment by MinIsMin** [comment]
Working now. Thanks!

Something I've noticed: When loaded an old logs and the corresponding shot logs, the focus is on the shot logs.
Try running around with Damagelog menu with old logs open: It works
Try running around with Damagelog menu with old logs with shot logs open: Doesn't work

**Comment by MrUnknownGamer** [comment]
Ill get that fixed then. I noticed that
